channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - Pillow
  - pytorch
  - torchvision
  - scikit-learn
  - scikit-image
  - tqdm
  - requests
  - pycocotools
  - pandas